### ISSUE TITLE
Icons not printing | firefox, chrome | Ubuntu 18.04

### ISSUE THREAD

**Issue by p-thor** [mephitrpg/rpg-cards#109]
Print fails to load icons. Only on chrome when option "background graphics" is ticket the cards print as intended.

**Comment by crobi** [comment]
This is known and stated in the help. 

Browsers dont print images unless you enable the "background graphics" option.

**Comment by p-thor** [comment]
Would changing it to img tags not work?

**Comment by crobi** [comment]
Using img tags would solve printing the icons, but it would still not print the card background color.

If you find a solution that works without using the background graphics option, feel free to post a PR!

**Comment by wereHamster** [comment]
The background color could be simulated using an absolutely-positioned img (generate the image in the browser using [HTMLCanvasElement toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) or perhaps simpler a svg (with a rect inside it and the background color as fill).

**Comment by crobi** [comment]
The colored card background has a radial gradient, generating an image for that sounds like a lot of work. Using a SVG [could work](https://www.w3schools.com/graphics/svg_grad_radial.asp) though. 

Note also that there is [a branch](https://github.com/crobi/rpg-cards/tree/web-components) that generates all icons using true vectorized SVG elements instead of DIV elements with rasterized background images.

**Comment by mephitrpg** [comment]
This is not a big deal, just check the "background graphics" option.

**Comment by mephitrpg** [comment]
This is not a big deal, just check the "background graphics" option.
