### ISSUE TITLE
Blank generate output or output generated as list of cards

### ISSUE THREAD

**Issue by CabbageW** [mephitrpg/rpg-cards#12]
Hello
I have to say first that I love the RPG card generator.

This is the problem however:
in Firefox when I press Generate the output.html file is blank.
in IE when I press Generate the cards generate in a vertical column and therefore I am getting 3 and a bit cards per page, it does not seem to be formatting correctly.

I've checked pop-up blockers and whitelisted the site in Firefox.  

Am I doing something wrong?

**Comment by crobi** [comment]
Works for me on Firefox 33.0.1 on windows. What version are you using, what operating system and what computer? Did you try pressing Generate a second time?

I didn't test the generator on IE. IE is not very good at supporting new web technologies, I should probably put a notice that IE is not officially supported.

**Comment by CabbageW** [comment]
Thanks for replying so quickly. 

I have the same version of Firefox on Windows 7 (Dell Laptop).  I've pressed Generate several times.

I have tried completely disabling Popup blocker.  That didn't seem to work either.

I hardly ever use IE, just thought I'd try it, by the way.

I was running No-Script and Ad Block (though I'd whitelisted the site), tried disabling them temporarily but that didn't seem to work either...

PS It's getting late here, so I'm off to bed now...

**Comment by crobi** [comment]
Could you please try it with all firefox addons disabled? I use firefox without any extensions or plugins and cannot reproduce this.

What this project needs to do is:
1. Let the user open `generate.html` and run scripts on it
2. Let the above page open a new tab that opens `output.html` and runs scripts on it
3. Let the first page communicate with the second page via `postMessage`

Steps 1-3 can be prevented by script blockers, step 2 can be prevented by ad blockers, and if your computer is _really_ slow, the second page will take too long to open so that it misses the communication with the first page.

**Comment by CabbageW** [comment]
That has fixed it thanks, I don't know which of my multitudinous add-ons was stopping it, but with them all disabled it has worked and I love the cards, thank you for the program and thank you for your help!
