### ISSUE TITLE
Samples Delete Cards

### ISSUE THREAD

**Issue by PhilosophasterDC** [mephitrpg/rpg-cards#127]
**Do you want to request a feature or report a bug?**
feature

**What is the current behavior?**
If you click the 'Load sample' button, it will replace the current deck. I recommend having it add them to the current deck, like what happens when you 'Load from file'

**Comment by henrygab** [comment]
Yes, please!  This simple change will enable saving multiple JSON files, each with specific subsets of cards defined, and then mix-n-match the results for a new printout.

It also avoids the screams of despair when loading the sample, and silently losing work done to add some existing cards.

@PhilosophasterDC … because the JSON files might define default values, what result when the newly loaded default value (e.g., default card colors, default backgrounds, etc.) differ from existing default values and selecting to load the samples (or load files)?

**Comment by mephitrpg** [comment]
New mantained fork https://github.com/crobi/rpg-cards/issues/159
