### ISSUE TITLE
RPG Cards do not generate properly in Safari

### ISSUE THREAD

**Issue by lotu** [mephitrpg/rpg-cards#22]
If you use RPG Cards it generates the cards in a single column in Safari 8.0.2.  It should generate them in a 3x3 pattern.
See this screen shot 
![of what safari generates](https://cloud.githubusercontent.com/assets/120244/6015510/416947fc-ab43-11e4-9552-67ae47f0007c.png) for the sample file.

(Also, thanks for making this I really, really, really love it a lot!!!!!)

**Comment by crobi** [comment]
I don't use Safari, so this might take a while.

According to [this](http://caniuse.com/#feat=flexbox), Safari does not support unprefixed CSS flexbox, so this might be the source of the problem. It would be also consistent with the symptoms you're seeing.

I'm not sure I want to mess with prefixed CSS definitions, especially since Safari is currently the only browser that does not support unprefixed flexbox. So if the above is true and you really want this project to work in the current version of Safari, feel free to try to fix it and post a pull request.

**Comment by lotu** [comment]
It is not a big deal for me to have this work in Safari.  An easy "patch"
would be to add some sort of message/pop up to Safari users letting them
know that there is a bug with rendering the cards and they can get it to
work by using Chrome or Firefox.  I was quite confused/frustrated until I
decided to try RPG Cards in Chrome myself.

**Comment by crobi** [comment]
`CSS.supports('flex', '1');` can be used to detect the support for CSS flexbox.

**Comment by wereHamster** [comment]
Rather than manually adding the prefixes, it would be more robust to post-process the css file with https://github.com/postcss/autoprefixer.

**Comment by crobi** [comment]
Thanks for the hint, I will add autoprefixer as a gulp task to the next major version.

@yuvalsapir: As I won't be doing any major development on the current branch, feel free to post a pull request for your quick fix.

**Comment by crobi** [comment]
Closing as safari now supports flexbox.
