### ISSUE TITLE
Card formats

### ISSUE THREAD

**Issue by Jackmunchkin** [mephitrpg/rpg-cards#25]
Hello

I am not a CSS specialist and though I tried to change card format in the CSS card format file, it does not seem to work…
I would like to suggest adding this format : 3.5 x 5.75 in in order to be able to print through a studio.
Maybe other formats from this printerstudio service would be interesting ! 
Besides, not sure it's an easy thing but would be interesting as well to generate JPG files of single cards.

http://www.printerstudio.com/personalized/blank_cards_custom_imprint_playing_cards_large_size.html

Thanks

**Comment by crobi** [comment]
Good idea. Currently the tool supports the standard bridge (2.25 x 3.5") and poker (2.5 x 3.5") card sizes, which seem to be the by far the most common. The poker size is also used by trading card games like Magic the Gathering. I have also randomly added (3.5 x 5.0") and (5.0 x 7.5") cards because you can comfortably print 2x2 and 1x2 of those on A4 or letter paper.

From looking at a couple of google results on custom card printing, the following sizes seem to be common as well and should be included:
- Large size (3.5 x 5.75")
- Tarot size (2.75 x 4.75")
- Mini size (1.75 x 2.5")
- Standard poker size (63 x 88mm, ca. 2.48 x 3.46")

If you know of any other commonly used sizes, let me know.

**Comment by crobi** [comment]
About the JPG export, do you need that for your print service? There are ways to do that from inside HTML/JavaScript ([here](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas) or [here](https://github.com/niklasvh/html2canvas)), but I'm not sure it will work well.

If you have a tool that can convert PDF to JPG (there's tons of those online), try the following: Export your deck with a custom page size equal to your card size. This way each page in the PDF contains one card without any borders. Then, export each PDF page to an image.

**Comment by janinko** [comment]
Any update on this issue? Adding more card sizes?

**Comment by crobi** [comment]
From the readme:

> I won't have time to work on this project in the forseeable future. PR's are still welcome, so feel free to implement new awesome features!

**Comment by mephitrpg** [comment]
New mantained fork https://github.com/crobi/rpg-cards/issues/159
