### ISSUE TITLE
Class icons won't show when genertating on Chrome

### ISSUE THREAD

**Issue by Orzpsd** [mephitrpg/rpg-cards#29]
The class icons won't show up on the back of the card when generating the card sheet on Chrome.

**Comment by crobi** [comment]
Works for me, can you describe your problem in detail?

**Comment by filipeamado** [comment]
When you try to print as pdf you must select the "Background graphics" option. that will solve the problem

**Comment by crobi** [comment]
Yes, that's why it's mentioned in the popup box with printing instructions.

There's no standard way of telling a browser to print background images. There's `-webkit-print-color-adjust: exact;`, which only works in Chrome, and is only a suggestion to the browser and always overridden by user settings..

There's also a [proposal for a new standard](https://wiki.csswg.org/ideas/print-backgrounds), but I'm not aware of any implementation of that.

**Comment by Orzpsd** [comment]
Sorry looks like the image didn't upload, it is only the class icons, not any others. 
![asd](https://cloud.githubusercontent.com/assets/11583240/6821555/a6c96066-d33c-11e4-8547-fc7177e6ea6e.PNG)

**Comment by Orzpsd** [comment]
Forgot to add, where on the purple one it should have the sorc class icon, this is a snippit of the pdf that was printed. As you can see, the background graphic is selected. I also may have or may have not forgotten I posted this bug. Also the class icon does show up on the preview.

**Comment by crobi** [comment]
what is the exact name of the icon you're trying to use?

**Comment by Orzpsd** [comment]
class-sorcerer, I tired with some other class icons and got the same result.

**Comment by crobi** [comment]
Should be fixed now
